[build]
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

# Redirections pour les différentes routes
[[redirects]]
  from = "/track"
  to = "/.netlify/functions/track"
  status = 200

[[redirects]]
  from = "/api"
  to = "/api.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers spécifiques pour les fonctions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"